sudo: required
services: 
    - docker

before_install:
    - docker build -t sumeetchawladocker/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sumeetchawladocker/react-test npm run test -- --coverage

    #taking images to docker hub
after_success:
    - docker build -t sumeetchawladocker/multi-client ./client
    - docker build -t sumeetchawladocker/multi-nginx ./nginx
    - docker build -t sumeetchawladocker/multi-server ./server
    - docker build -t sumeetchawladocker/multi-worker ./worker


    #Docker login using CLI and Travin Enviornment variables
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push images to docker hub
    - docker push sumeetchawladocker/multi-client
    - docker push sumeetchawladocker/multi-nginx
    - docker push sumeetchawladocker/multi-server
    - docker push sumeetchawladocker/multi-worker
